---
title: 'Section C: Distribution of Teacher Resources in Washington'
author: "Pooya Almasi"
date: "`r format(Sys.Date(), format = '%B %d, %Y')`"
output: 
  html_document:
        fig_width: 8
        toc_float: true
        toc: true
knit: (function(input, encoding) rmarkdown::render(input, output_file = "index.html"))
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      comment = NA, 
                      cache = TRUE,
                      warning = FALSE,
                      message = FALSE, 
                      cache.lazy = FALSE,
                      fig.align = "center"
                      )
```


```{r data, include=FALSE}

library(tidyverse)
library(googledrive)
library(haven)


id_s275_2015_2019 <- drive_get(as_id("https://drive.google.com/file/d/1wV5hiz5lJvHC-FljTl4Np1UynNoLTP88/view?usp=sharing"))

id_s275_2020<- drive_get(as_id("https://drive.google.com/file/d/1weEr_ZuFLyKYxPE_raj_6pWnov-2yJd2/view?usp=sharing"))

id_f196 <- drive_get(as_id("https://drive.google.com/file/d/1sGIIj3hplOHq7qPL7S7YTmQByzuCcHVU/view?usp=sharing"))

id_demos <- drive_get(as_id("https://drive.google.com/file/d/1C2Kt_DsoYlz2eB-8z9SB97d5-G2jmYKc/view?usp=sharing"))

df_s275_2015_2019 <- id_s275_2015_2019 %>%
  drive_read_raw() %>%
  read_dta()

df_s275_2020 <- id_s275_2020 %>%
  drive_read_raw() %>%
  read_dta()

df_f196 <- id_f196 %>%
  drive_read_raw() %>%
  read_dta()

df_demos <- id_demos %>%
  drive_read_raw() %>%
  read_dta()

df_s275_raw <- bind_rows(df_s275_2015_2019, df_s275_2020)

df_s275_raw <- df_s275_raw %>%
  mutate(cou_s = str_pad(as.character(cou), 2, side="left", pad="0"),
         dis_s = str_pad(as.character(dis), 3, side="left", pad="0"),
         coudis_s=paste(cou_s, dis_s, sep=""))

df_s275_raw <- full_join(df_s275_raw, df_f196, by=c("coudis_s"="coudis", "schyear"="schyear"))

df_s275_raw <- full_join(df_s275_raw, df_demos, by=c("coudis_s"="coudis_s", "schyear"="schyr"))

df_s275 <- df_s275_raw %>%
  filter(droot == 31 | droot == 32 | droot == 33 | droot == 34) %>%
  filter(certfte > 0.5) %>% 
  mutate(lname = str_to_lower(str_trim(LastName)),
         fname = str_to_lower(str_trim(FirstName)),
         mname = str_to_lower(str_trim(MiddleName))) %>%
  distinct_at(vars(schyear, lname, fname, mname, certfte, exp, othersal, 
                   tfinsal, certbase, clasbase, cert, coudis_s), 
              .keep_all = TRUE) 

```


C.1 Regionalization Factor Bar Graph separately for 2018-19; 2019-20 (difference in regionalization factor levels between years): 
       G1=1; men=average poverty rate; women=average share of students of color
```{r C1}


df_s275 %>% 
  filter(SchoolYear == "2018-2019" & !is.na(rfactor_cis_2019)) %>% 
  mutate(rfactor = as.character(rfactor_cis_2019)) %>% 
  group_by(rfactor) %>% 
  summarize(pctstu_nonwhite = mean(1 - dis_pctstu_white, na.rm = TRUE),
            pctstu_frpl = mean(dis_pctstu_frl, na.rm = TRUE)) %>% 
  pivot_longer(c(pctstu_nonwhite, pctstu_frpl), names_to = "var", values_to = "val") %>% 
  ggplot(aes(x = rfactor, y = val, fill = var)) +
  geom_col(position = "dodge", width = 0.7) + 
  geom_text(aes(label = round(val*100, digits = 1)), position = position_dodge(width = 0.7), vjust = -0.25, size = 3.5) +
  scale_fill_discrete(name = "", 
                      breaks = c("pctstu_nonwhite", "pctstu_frpl"),
                      labels = c("% of non-white students", "% of students receiving FRPL")) + 
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), limits = c(0, 0.7)) +
  labs(x = "Regionalization Factor",
       y = "",
       title = "Regionalization factor by share of non-white students and FRPL for AY 2018-2019")


df_s275 %>% 
  filter(SchoolYear == "2018-2019" & !is.na(rfactor_cis_2019)) %>% 
  mutate(rfactor = as.character(rfactor_cis_2019)) %>% 
  group_by(rfactor) %>% 
  summarize(pctstu_nonwhite = mean(1 - dis_pctstu_white, na.rm = TRUE),
            pctstu_hispanic = mean(dis_pctstu_hispanic, na.rm = TRUE),
            pctstu_black = mean(dis_pctstu_black, na.rm = TRUE),
            pctstu_frpl = mean(dis_pctstu_frl, na.rm = TRUE)) %>% 
  pivot_longer(c(pctstu_nonwhite, pctstu_hispanic, pctstu_black, pctstu_frpl), names_to = "var", values_to = "val") %>% 
  ggplot(aes(x = var, y = val, fill = rfactor)) +
  geom_col(position = "dodge", width = 0.6) + 
  geom_text(aes(label = round(val*100, digits = 1)), position = position_dodge(width = 0.6), vjust = -0.25, size = 3) +
  scale_x_discrete(name = "",
                   limits = c("pctstu_nonwhite", "pctstu_hispanic", "pctstu_black", "pctstu_frpl"),
                   labels = c("% of non-white students", "% of hispanic students",
                              "% of black students", "% of students receiving FRPL")) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), limits = c(0, 0.65)) +
  labs(fill = "Regionalization Factor",
       x = "",
       y = "",
       title = "Share of students of color and FRPL by Regionalization factor for AY 2018-2019")
  
  
df_s275 %>% 
  filter(SchoolYear == "2018-2019" & !is.na(rfactor_cis_2019)) %>% 
  group_by(codist) %>% 
  summarize(pctstu_nonwhite = mean(1 - dis_pctstu_white, na.rm = TRUE),
            pctstu_frpl = mean(dis_pctstu_frl, na.rm = TRUE)) %>% 
  ggplot(aes(x = pctstu_nonwhite, pctstu_frpl)) +
  geom_point() +
  geom_smooth(method='lm', formula= y~x) +
  labs(x = "Share of non-white students",
       y = "Share of students receiving FRPL",
       title = "Scatterplot of share of non-white students and share of students receiving FRPL in AY 2018-2019")


df_s275 %>% 
  filter(SchoolYear == "2018-2019" & !is.na(rfactor_cis_2019)) %>% 
  mutate(rfactor = as.character(rfactor_cis_2019)) %>% 
  group_by(codist, rfactor) %>%
  summarize(pctstu_nonwhite = mean(1 - dis_pctstu_white, na.rm = TRUE),
            pctstu_frpl = mean(dis_pctstu_frl, na.rm = TRUE)) %>%
  ggplot(aes(x = pctstu_nonwhite, pctstu_frpl)) +
  geom_point() +
  geom_smooth(method='lm', formula= y~x) + 
  facet_wrap(~ rfactor) +
  labs(x = "Share of non-white students",
       y = "Share of students receiving FRPL",
       title = "Scatterplot of share of non-white students and share of students receiving FRPL by regionalization factor in AY 2018-2019")


```

```{r C2}

```

```{r C3}

```

```{r C4}

```

```{r C5}

```

```{r C6}

```

```{r C7}

```
