---
title: "pdf scrape"
author: "Alex Liu"
date: "10/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r wd}
setwd("/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset")
```

```{r packages}
library(tidyverse)
library(rJava)
library(tabulizer)
library(exploratory)
#library(formattable)
library(scales)
```

```{r enroll six}
df <- extract_tables("/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/pdf_dataset/6th_Monthly Enrollment.pdf",
                     output = "data.frame",
                     guess = FALSE)

#write.csv(df[[1]], 
#          "/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/raw/raw_enrollment_six.csv",
#          row.names=FALSE)

enroll_six <- df[[1]] %>%
  slice(6:29)


colmn1 <- c("October", "October_6th", "November", "November_6th")
colmn2 <- c("December", "December_6th", "January", "January_6th")
colmn3 <- c("February", "February_6th")

enroll_six <- separate(data = enroll_six,
                 col = Select.View.,
                 sep = " ",
                 into = colmn1,
                 remove = TRUE) 
enroll_six <- separate(data = enroll_six, 
                       col = Filter.by.Grade.Levels, 
                       sep = " ", 
                       into = colmn2, 
                       remove = TRUE)

enroll_six <- separate(data = enroll_six,
                       col = X.1,
                       sep = " ",
                       into = colmn3,
                       remove = TRUE)

for (i in 2: ncol(enroll_six)) {
  enroll_six[i] <- lapply(enroll_six[i],
                          function(x){as.numeric(as.character(gsub(",", "", x)))})
}


enrollment_six <- write.csv(enroll_six, "/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/enrollment_six.csv",
                            row.names=FALSE)

```

```{r not used}
#test <- as.character(enroll_six$Select.View.) %>%
#  str_split(pattern = " ")
```


```{r enroll_nine}
df <- extract_tables("/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/pdf_dataset/9th_Monthly Enrollment.pdf",
                     output = "data.frame",
                     guess = FALSE)

#write.csv(df[[1]], 
#          "/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/raw/raw_enrollment_nine.csv",
#          row.names=FALSE)

enroll_nine <- df[[1]] %>%
  slice(6:29)

colmn1 <- c("October", "October_9th", "November", "November_9th")
colmn2 <- c("December", "December_9th", "January", "January_9th")
colmn3 <- c("February", "February_9th")

enroll_nine <- separate(data = enroll_nine,
                 col = Select.View.,
                 sep = " ",
                 into = colmn1,
                 remove = TRUE) 
enroll_nine <- separate(data = enroll_nine, 
                       col = Filter.by.Grade.Levels, 
                       sep = " ", 
                       into = colmn2, 
                       remove = TRUE)

enroll_nine <- separate(data = enroll_nine,
                       col = X.1,
                       sep = " ",
                       into = colmn3,
                       remove = TRUE)

for (i in 2: ncol(enroll_nine)) {
  enroll_nine[i] <- lapply(enroll_nine[i],
                          function(x){as.numeric(as.character(gsub(",", "", x)))})
}


enrollment_nine <- write.csv(enroll_nine, "/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/enrollment_nine.csv",
                            row.names=FALSE)
```


```{r enroll kindergarten}
df <- extract_tables("/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/pdf_dataset/Kindergarten_Monthly Enrollment.pdf",
                     output = "data.frame",
                     guess = FALSE)

#write.csv(df[[1]], 
#          "/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/raw/raw_enrollment_kindergarten.csv",
#          row.names=FALSE)

enroll_kindergarten <- df[[1]] %>%
  slice(6:29)

colmn1 <- c("October", "October_9th", "November", "November_9th", "December")
colmn2 <- c("December_9th", "January", "January_9th")
colmn3 <- c("February", "February_9th")

enroll_kindergarten <- separate(data = enroll_kindergarten,
                                col = Select.View.,
                                sep = " ",
                                into = colmn1,
                                remove = TRUE) 
enroll_kindergarten <- separate(data = enroll_kindergarten, 
                                col = Filter.by.Grade.Levels, 
                                sep = " ", 
                                into = colmn2, 
                                remove = TRUE)

enroll_kindergarten <- separate(data = enroll_kindergarten,
                                col = X.1,
                                sep = " ",
                                into = colmn3,
                                remove = TRUE)

for (i in 2: ncol(enroll_kindergarten)) {
  enroll_kindergarten[i] <- lapply(enroll_kindergarten[i],
                          function(x){as.numeric(as.character(gsub(",", "", x)))})
}

# the row "Gender X" need to be corrected
#is.na(enroll_kindergarten)
enroll_kindergarten[8,2:11] <- c(42, 61, 43, 60, 44, 60, 45, 60, 43, 60)
write.csv(enroll_kindergarten, "/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/enrollment_kindergarten.csv",
                            row.names=FALSE)

```


```{r change_enroll_six}
df1 <- extract_tables("/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/pdf_dataset/6th_Monthly Enrollment Change.pdf",
                     output = "data.frame",
                     guess = FALSE)

#write.csv(df1[[1]], 
#          "/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/raw/raw_change_enrollment_six.csv",
#          row.names=FALSE)

change_enroll_six <- df1[[1]] %>%
  slice(6:28)

colmn1 <- c("StudentGroup", "October", "November")
colmn2 <- c("December", "January")

change_enroll_six <- separate(data = change_enroll_six, 
                                col = Filter.by.Grade.Levels, 
                                sep = " ", 
                                into = colmn2, 
                                remove = TRUE) 
names(change_enroll_six)[names(change_enroll_six) == "X"] <- "February"

change_enroll_six <- separate(data = change_enroll_six,
                                col = Select.View.,
                                sep = "(?<=[ ])(?=[0-9 -])",
                                into = colmn1,
                                remove = TRUE) 

change_enroll_six[18, 1:3] <- c("Non Section 504", "-4.8%", "-4.9%")
change_enroll_six[19, 1:3] <- c("Section 504", "-6.9%", "-7.3%")
change_enroll_six[1, 1] <- "All Students"

change_enroll_six[2:6] <- sapply(change_enroll_six[2:6], 
                                 function(x) as.numeric(sub("%","",x))/100)


#change_enroll_six[2:6] <- sapply(change_enroll_six[2:6], 
#                                 function(x) percent(x, accuracy=0.1))


write.csv(change_enroll_six, "/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/change_enrollment_six.csv",
                            row.names=FALSE)
```


```{r change_enroll_nine}
df1 <- extract_tables("/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/pdf_dataset/9th_Monthly Enrollment Change.pdf",
                     output = "data.frame",
                     guess = FALSE)

#write.csv(df1[[1]], 
#          "/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/raw/raw_change_enrollment_nine.csv",
#          row.names=FALSE)

change_enroll_nine <- df1[[1]] %>%
  slice(6:28)

colmn1 <- c("StudentGroup", "October", "November")
colmn2 <- c("December", "January")

change_enroll_nine <- separate(data = change_enroll_nine, 
                                col = Filter.by.Grade.Levels, 
                                sep = " ", 
                                into = colmn2, 
                                remove = TRUE) 
names(change_enroll_nine)[names(change_enroll_nine) == "X"] <- "February"

change_enroll_nine <- separate(data = change_enroll_nine,
                                col = Select.View.,
                                sep = "(?<=[ ])(?=[0-9 -])",
                                into = colmn1,
                                remove = TRUE) 

change_enroll_nine[18, 1:3] <- c("Non Section 504", "0.3%", "0.2%")
change_enroll_nine[19, 1:3] <- c("Section 504", "8.4%", "8.2%")
change_enroll_nine[1, 1] <- "All Students"

change_enroll_nine[2:6] <- sapply(change_enroll_nine[2:6], 
                                 function(x) as.numeric(sub("%","",x))/100)

#change_enroll_nine[2:6] <- sapply(change_enroll_nine[2:6], 
#                                 function(x) percent(x, accuracy=0.1))


write.csv(change_enroll_nine, "/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/change_enrollment_nine.csv",
                            row.names=FALSE)


```


```{r change_enroll_kindergarten}
df1 <- extract_tables("/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/pdf_dataset/Kindergarten_Monthly Enrollment Change.pdf",
                     output = "data.frame",
                     guess = FALSE)

#write.csv(df1[[1]], 
#          "/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/raw/raw_change_enrollment_kindergarten.csv",
#          row.names=FALSE)

change_enroll_kid <- df1[[1]] %>%
  slice(6:28)

colmn1 <- c("StudentGroup", "October", "November")
colmn2 <- c("December", "January")

change_enroll_kid <- separate(data = change_enroll_kid, 
                                col = Filter.by.Grade.Levels, 
                                sep = " ", 
                                into = colmn2, 
                                remove = TRUE) 
names(change_enroll_kid)[names(change_enroll_kid) == "X"] <- "February"

change_enroll_kid <- separate(data = change_enroll_kid,
                                col = Select.View.,
                                sep = "(?<=[ ])(?=[0-9 -])",
                                into = colmn1,
                                remove = TRUE) 

change_enroll_kid[18, 1:3] <- c("Non Section 504", "-14.0%", "-13.9%")
change_enroll_kid[19, 1:3] <- c("Section 504", "-20.5%", "-20.2%")
change_enroll_kid[1, 1] <- "All Students"

change_enroll_kid[2:6] <- sapply(change_enroll_kid[2:6], 
                                 function(x) as.numeric(sub("%","",x))/100)

#change_enroll_kid[2:6] <- sapply(change_enroll_kid[2:6], 
#                                 function(x) percent(x, accuracy=0.1))


write.csv(change_enroll_kid, "/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/change_enrollment_kindergarten.csv",
                            row.names=FALSE)

```

```{r absences raw data}

setwd("/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/pdf_dataset")
absences_files <- list.files(pattern = "*Absences.pdf$")
output <- vector("list", length(absences_files))
df_absences <- vector("list", length(absences_files))
grade_level <- vector("list", length(absences_files))

for (i in seq_along(absences_files)) {
  output[[i]] <- extract_tables(absences_files[[i]],
                     output = "data.frame",
                     guess = FALSE) 
  df_absences[[i]] <- output[[i]][[1]]
  grade_level[[i]] <- df_absences[[i]][1,2]
}

names(df_absences) = grade_level

write.csv(df_absences[["10th Grade"]], 
          "/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/raw/raw_10th_Absences.csv",
          row.names=FALSE)

write.csv(df_absences[["9th Grade"]], 
          "/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/raw/raw_9th_Absences.csv",
          row.names=FALSE)

write.csv(df_absences[["8th Grade"]], 
          "/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/raw/raw_8th_Absences.csv",
          row.names=FALSE)

write.csv(df_absences[["6th Grade"]], 
          "/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/raw/raw_6th_Absences.csv",
          row.names=FALSE)

write.csv(df_absences[["3rd Grade"]], 
          "/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/raw/raw_3rd_Absences.csv",
          row.names=FALSE)

write.csv(df_absences[["Kindergarten"]], 
          "/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/raw/raw_Kindergarten_Absences.csv",
          row.names=FALSE)
```

```{r absences prek}
absences_prek <- read.csv("/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/raw/raw_Kindergarten_Absences.csv") %>%
  slice(7:29)

colmn1 <- c("10/2019", "10/2020", "10/2021", 
            "11/2019", "11/2020", "11/2021", "12/2019")
colmn2 <- c("12/2020", "12/2021", "01/2019", "01/2020")
colmn3 <- c("01/2021", "02/2019", "02/2020", "02/2021")

absences_prek <- separate(data = absences_prek, 
                                col = Select.View., 
                                sep = " ", 
                                into = colmn1, 
                                remove = TRUE) 
absences_prek <- separate(data = absences_prek, 
                                col = Filter.by.Grade.Levels, 
                                sep = " ", 
                                into = colmn2, 
                                remove = TRUE) 
absences_prek <- separate(data = absences_prek, 
                                col = X.1, 
                                sep = " ", 
                                into = colmn3, 
                                remove = TRUE) 

months <-c(" ", "October", "October", "October", 
           "November", "November", "November",
           "December", "December", "December",
           "January", "January", "January",
           "February", "February", "February" ) 
years <- c(" ", "2019", "2020", "2021",
           "2019", "2020", "2021",
           "2019", "2020", "2021",
           "2019", "2020", "2021",
           "2019", "2020", "2021")
names(absences_prek)[1] <- "StudentGroup"
absences_prek[1, 1] <- "All Students"
absences_prek <- rbind(months, years, absences_prek)

write.csv(absences_prek, 
          "/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/absences_prek.csv",
          row.names=FALSE)

```

```{r absences 3rd}
absences_3rd <- read.csv("/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/raw/raw_3rd_Absences.csv") %>%
  slice(7:29)

colmn1 <- c("10/2019", "10/2020", "10/2021", 
            "11/2019", "11/2020", "11/2021")
colmn2 <- c("12/2019", "12/2020", "12/2021", 
            "01/2019", "01/2020")
colmn3 <- c("01/2021", "02/2019", "02/2020", "02/2021")

absences_3rd <- separate(data = absences_3rd, 
                                col = Select.View., 
                                sep = " ", 
                                into = colmn1, 
                                remove = TRUE) 
absences_3rd <- separate(data = absences_3rd, 
                                col = Filter.by.Grade.Levels, 
                                sep = " ", 
                                into = colmn2, 
                                remove = TRUE) 
absences_3rd <- separate(data = absences_3rd, 
                                col = X.1, 
                                sep = " ", 
                                into = colmn3, 
                                remove = TRUE) 

months <-c(" ", "October", "October", "October", 
           "November", "November", "November",
           "December", "December", "December",
           "January", "January", "January",
           "February", "February", "February" ) 
years <- c(" ", "2019", "2020", "2021",
           "2019", "2020", "2021",
           "2019", "2020", "2021",
           "2019", "2020", "2021",
           "2019", "2020", "2021")
names(absences_3rd)[1] <- "StudentGroup"
absences_3rd[1, 1] <- "All Students"
absences_3rd <- rbind(months, years, absences_3rd)

write.csv(absences_3rd, 
          "/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/absences_3rd.csv",
          row.names=FALSE)

```

```{r absences 6th}
absences_6th <- read.csv("/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/raw/raw_6th_Absences.csv") %>%
  slice(7:29)

colmn1 <- c("10/2019", "10/2020", "10/2021", 
            "11/2019", "11/2020", "11/2021")
colmn2 <- c("12/2019", "12/2020", "12/2021", 
            "01/2019", "01/2020")
colmn3 <- c("01/2021", "02/2019", "02/2020", "02/2021")

absences_6th <- separate(data = absences_6th, 
                                col = Select.View., 
                                sep = " ", 
                                into = colmn1, 
                                remove = TRUE) 
absences_6th <- separate(data = absences_6th, 
                                col = Filter.by.Grade.Levels, 
                                sep = " ", 
                                into = colmn2, 
                                remove = TRUE) 
absences_6th <- separate(data = absences_6th, 
                                col = X.1, 
                                sep = " ", 
                                into = colmn3, 
                                remove = TRUE) 

months <-c(" ", "October", "October", "October", 
           "November", "November", "November",
           "December", "December", "December",
           "January", "January", "January",
           "February", "February", "February" ) 
years <- c(" ", "2019", "2020", "2021",
           "2019", "2020", "2021",
           "2019", "2020", "2021",
           "2019", "2020", "2021",
           "2019", "2020", "2021")
names(absences_6th)[1] <- "StudentGroup"
absences_6th[1, 1] <- "All Students"
absences_6th <- rbind(months, years, absences_6th)

write.csv(absences_6th, 
          "/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/absences_6th.csv",
          row.names=FALSE)
```


```{r absences 8th}
absences_8th <- read.csv("/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/raw/raw_8th_Absences.csv") %>%
  slice(7:29)

colmn1 <- c("10/2019", "10/2020", "10/2021", 
            "11/2019", "11/2020", "11/2021")
colmn2 <- c("12/2019", "12/2020", "12/2021", 
            "01/2019", "01/2020")
colmn3 <- c("01/2021", "02/2019", "02/2020", "02/2021")

absences_8th <- separate(data = absences_8th, 
                                col = Select.View., 
                                sep = " ", 
                                into = colmn1, 
                                remove = TRUE) 
absences_8th <- separate(data = absences_8th, 
                                col = Filter.by.Grade.Levels, 
                                sep = " ", 
                                into = colmn2, 
                                remove = TRUE) 
absences_8th <- separate(data = absences_8th, 
                                col = X.1, 
                                sep = " ", 
                                into = colmn3, 
                                remove = TRUE) 

months <-c(" ", "October", "October", "October", 
           "November", "November", "November",
           "December", "December", "December",
           "January", "January", "January",
           "February", "February", "February" ) 
years <- c(" ", "2019", "2020", "2021",
           "2019", "2020", "2021",
           "2019", "2020", "2021",
           "2019", "2020", "2021",
           "2019", "2020", "2021")
names(absences_8th)[1] <- "StudentGroup"
absences_8th[1, 1] <- "All Students"
absences_8th <- rbind(months, years, absences_8th)

write.csv(absences_8th, 
          "/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/absences_8th.csv",
          row.names=FALSE)
```

```{r absences 9th}
absences_9th <- read.csv("/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/raw/raw_9th_Absences.csv") %>%
  slice(7:29)

colmn1 <- c("10/2019", "10/2020", "10/2021", 
            "11/2019", "11/2020", "11/2021")
colmn2 <- c("12/2019", "12/2020", "12/2021", 
            "01/2019", "01/2020")
colmn3 <- c("01/2021", "02/2019", "02/2020", "02/2021")

absences_9th <- separate(data = absences_9th, 
                                col = Select.View., 
                                sep = " ", 
                                into = colmn1, 
                                remove = TRUE) 
absences_9th <- separate(data = absences_9th, 
                                col = Filter.by.Grade.Levels, 
                                sep = " ", 
                                into = colmn2, 
                                remove = TRUE) 
absences_9th <- separate(data = absences_9th, 
                                col = X.1, 
                                sep = " ", 
                                into = colmn3, 
                                remove = TRUE) 

months <-c(" ", "October", "October", "October", 
           "November", "November", "November",
           "December", "December", "December",
           "January", "January", "January",
           "February", "February", "February" ) 
years <- c(" ", "2019", "2020", "2021",
           "2019", "2020", "2021",
           "2019", "2020", "2021",
           "2019", "2020", "2021",
           "2019", "2020", "2021")
names(absences_9th)[1] <- "StudentGroup"
absences_9th[1, 1] <- "All Students"
absences_9th <- rbind(months, years, absences_9th)

write.csv(absences_9th, 
          "/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/absences_9th.csv",
          row.names=FALSE)

```


```{r absences 10th}
absences_10th <- read.csv("/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/raw/raw_10th_Absences.csv") %>%
  slice(7:29)

colmn1 <- c("10/2019", "10/2020", "10/2021", 
            "11/2019", "11/2020", "11/2021")
colmn2 <- c("12/2019", "12/2020", "12/2021", 
            "01/2019", "01/2020")
colmn3 <- c("01/2021", "02/2019", "02/2020", "02/2021")

absences_10th <- separate(data = absences_10th, 
                                col = Select.View., 
                                sep = " ", 
                                into = colmn1, 
                                remove = TRUE) 
absences_10th <- separate(data = absences_10th, 
                                col = Filter.by.Grade.Levels, 
                                sep = " ", 
                                into = colmn2, 
                                remove = TRUE) 
absences_10th <- separate(data = absences_10th, 
                                col = X.1, 
                                sep = " ", 
                                into = colmn3, 
                                remove = TRUE) 

months <-c("", "October", "October", "October", 
           "November", "November", "November",
           "December", "December", "December",
           "January", "January", "January",
           "February", "February", "February" ) 
years <- c("", "2019", "2020", "2021",
           "2019", "2020", "2021",
           "2019", "2020", "2021",
           "2019", "2020", "2021",
           "2019", "2020", "2021")
names(absences_10th)[1] <- "StudentGroup"
absences_10th[1, 1] <- "All Students"
absences_10th <- rbind(months, years, absences_10th)

write.csv(absences_10th, 
          "/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/absences_10th.csv",
          row.names=FALSE)

```


```{r nonpassing income data, message=FALSE, warning=FALSE}
setwd("/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/pdf_dataset/non_passing_byincome")

district_files <- list.files(pattern = "*.pdf$")
output <- vector("list", length(district_files))
raw_output <- vector("list", length(district_files))

colmn1 <- c("GradeLevel", "2018-19", "add1")
colmn2 <- c("2019-20", "2020-21", "add2")

for (i in seq_along(district_files)) {
  df <- extract_tables(district_files[[i]],
                     output = "data.frame",
                     guess = FALSE)
  raw_output[[i]] <- df[[1]]
  
  r <- grep("^Al Grades", df[[1]][ ,1])
  `Low-Income` <- df[[1]][r[1], ]
  `Non-Low Income` <- df[[1]][r[2], ]
  
  output[[i]] <- bind_rows(df[[1]][r[1], ], df[[1]][r[2], ]) %>%
    mutate(District = df[[1]][1, 2]) %>%
    mutate(StudentGroup = c("Low-Income", "Non-Low Income"))
  
  output[[i]] <- separate(data = output[[i]], 
                          col = X, 
                          sep = "(?<=[ ])(?=[0-9 * S])", 
                          into = colmn1, 
                          remove = FALSE)
  
  output[[i]] <- separate(data = output[[i]], 
                          col = Student.Course.Outcomes, 
                          sep = "(?<=[ ])(?=[0-9 * S])",  
                          into = colmn2, 
                          remove = FALSE) 
}

df_district_nonpass_byinc <- bind_rows(output)

write.csv(df_district_nonpass_byinc, 
          "/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/raw/raw_nonpass_district_byinc.csv",
          row.names=FALSE)
```

```{r numericl fail income data, message=FALSE, warning=FALSE}
setwd("/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/pdf_dataset/num_fail_byincome")

district_files <- list.files(pattern = "*.pdf$")
output <- vector("list", length(district_files))
raw_output <- vector("list", length(district_files))

colmn1 <- c("GradeLevel", "2018-19", "add1")
colmn2 <- c("2019-20", "2020-21", "add2")

for (i in seq_along(district_files)) {
  df <- extract_tables(district_files[[i]],
                     output = "data.frame",
                     guess = FALSE)
  raw_output[[i]] <- df[[1]]
  
  r <- grep("^Al Grades", df[[1]][ ,1])
  `Low-Income` <- df[[1]][r[1], ]
  `Non-Low Income` <- df[[1]][r[2], ]
  
  output[[i]] <- bind_rows(df[[1]][r[1], ], df[[1]][r[2], ]) %>%
    mutate(District = df[[1]][1, 2]) %>%
    mutate(StudentGroup = c("Low-Income", "Non-Low Income"))
  
  output[[i]] <- separate(data = output[[i]], 
                          col = X, 
                          sep = "(?<=[ ])(?=[0-9 * S])", 
                          into = colmn1, 
                          remove = FALSE)
  
  output[[i]] <- separate(data = output[[i]], 
                          col = Student.Course.Outcomes, 
                          sep = "(?<=[ ])(?=[0-9 * S])",  
                          into = colmn2, 
                          remove = FALSE) 
}

df_district_nonpass_byinc <- bind_rows(output)

write.csv(df_district_nonpass_byinc, 
          "/Users/alexliu/Documents/GitHub/evidenceforequity/A/enrollment_absence_dataset/raw/raw_numfail_district_byinc.csv",
          row.names=FALSE)

```



