---
title: 'Section D: Impact and Implications of COVID-specific Policies/Funds'
author: "Alex Liu"
date: "`r format(Sys.Date(), format = '%B %d, %Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    fig_width: 8
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      comment = NA, 
                      cache = TRUE,
                      warning = FALSE,
                      message = FALSE, 
                      cache.lazy = FALSE,
                      fig.align = "center"
                      )
```


```{r data, include=FALSE}
library(tidyverse)
library(googledrive)

id_LEA_plans <- drive_get(as_id("https://drive.google.com/file/d/1Yc35em3KL-06Cau-Iy0GBdvyPLO01CRu/view?usp=sharing"))


df_LEA_plans <- id_LEA_plans %>%
  drive_read_string() %>%
  read_csv(col_names=TRUE)
```

```{r libraries, include=FALSE}
library(googledrive)
library(tidyverse)
library(ggplot2)
library(formattable)
library(reshape2)
library(grid)
library(gridExtra)
library(sf)
library(spData)
library(leaidr)

#library(rJava)
#library(tabulizer) 
```

```{r uw_palette, include=FALSE}
# from purple to gold (low=gold, high=purple)
uw_palette <- colorRampPalette(c("#4b2e83", "#e8e3d3"))
uw_reverse <- colorRampPalette(c("#e8e3d3", "#4b2e83"))
black_white <- colorRampPalette(c("white", "black"))
```


```{r A.5.2.iv graduation pathway agg state total w nopath by inc, eval=FALSE, include=FALSE}

#change in selection of pathways
plotting_pathways <- factor(c("ELA and Math Both",
                              "CTE",
                              "ASVAB",
                              "ELA Assessment",
                              "ELA Course",        
                              "Math Assessment",
                              "Math Course"), 
                            levels = c("ELA and Math Both",
                              "CTE",
                              "ASVAB",
                              "ELA Assessment",
                              "ELA Course",        
                              "Math Assessment",
                              "Math Course"))

no_pathways <- long_state_grad_path %>%
  filter(Pathways == "% No Pathway",
         StudentGroup %in% c("Low-Income ", "All Students ")) %>%
  mutate(Pathways = "No Pathway",
         StudentGroup = c("All Students", "Low-Income"))
colnames(no_pathways)[1] <- "Student Group"

long_state_agg_path_inc <- state_agg_path %>%
  select("Student Group", all_of(plotting_pathways)) %>%
  filter(`Student Group` %in% income_group) %>%
  melt(., id.vars = "Student Group",
       measure.vars = plotting_pathways,
       variable.name = "Pathways",
       value.name="% Completed") %>%
  bind_rows(., no_pathways) %>%
  arrange(`Student Group`, Pathways)

long_state_agg_path_inc %>%
  ggplot(aes(fill= fct_rev(`Pathways`),
             x= `Student Group`, 
             y= `% Completed`)) + 
  geom_col(position="dodge", width = 0.9) +
  ggtitle("Class of 2020 Graduation Pathways") +
  labs(x = "Student Groups", 
       y = "Percentage of Students Completed",
       caption = "Data is unavailable for percent of non-low income students that did not meet graduation pathways") +
  scale_y_continuous(labels = percent, limits = c(0, 1)) +
  scale_fill_manual(name ="Pathways", values = uw_reverse(8)) +
  geom_text(aes(label = `% Completed` ), position = position_dodge(0.9),
            hjust = -0.1, vjust = 0.4, colour = "black", size = 1.5) +
  theme_light() +
  coord_flip() +
  guides(fill = guide_legend(reverse = TRUE)) +
  theme(plot.title = element_text(face = "bold", size = 14, hjust = 0.45),
        plot.subtitle = element_text(hjust = 0.5),
        plot.caption = element_text(hjust = 0.5, size = 9),
        legend.background = element_rect(fill = "white", size = 1, colour = "white"),
        legend.title=element_text(size = 10),
        legend.text=element_text(size = 7),
        axis.text.x  = element_text(angle=45, vjust=0.5, size=7),
        axis.title.x  = element_text(size=12),
        axis.title.y  = element_text(size=12),
        strip.text.x = element_text(size = 12, colour = "black"))

#ggsave("/Users/alexliu/Desktop/A.5.2.iv graduation pathway agg state total w nopath by inc.png")
```



